apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-0
  namespace: free5gc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: ""
  volumeMode: Filesystem
