apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-0
  labels:
    project: free5gc
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: free5gc
    name: datadir-mongodb-0
  local:
    path: /home/ubuntu/kubedata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-113-255.ec2.internal
