apiVersion: v1
kind: Pod
metadata:
  name: longhorn-samplepod
spec:
  containers:
  - name: longhorn-sample-container
    image: amazonlinux:latest
    command: ["/bin/sh", "-c", "trap : TERM INT; touch /mnt/SUCCESS; sleep infinity & wait"]
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: longhorn-pvc
