apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vfio-dpdk-hostdevice-net-1
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "host-device",
        "pciBusID": "0000:00:07.0",
        "ipam": {
                "type": "static",
                "addresses": [
                    {
                        "address": "10.0.10.93/24",
                        "gateway": "0.0.0.0"
                    }
                ],
                "routes": [
                    { "dst": "10.0.10.0/24", "gw": "0.0.0.0" }
                ]
            }
          }'
# eth0 from VPC CNI, net1 from host-device ENI with vfio-pci driver, bound using dpdk-devbind.py, for dpdk traffic
# kubectl get network-attachment-definitions
# "pciBusID": "0000:00:07.0" is from SRIOV-DP configmap:
#            {
#                "resourceName": "sriov_netdevice_2",
#                "selectors": {
#                    "vendors": [
#                        "1d0f"
#                    ],
#                    "devices": [
#                        "ec20"
#                    ],
#                    "drivers": [
#                        "ena",
#                        "igb_uio",
#                        "vfio-pci"
#                    ],
#                    "pciAddresses": [
#                        "0000:00:07.0"
#                    ]
#                }
#
# "pciBusID": "0000:00:07.0" bound to VFIO driver for DPDK
# [root@ip-172-31-148-193 custom-ami-scripts]# ./dpdk-devbind.py -s
# 
# Network devices using DPDK-compatible driver
# ============================================
# 0000:00:07.0 'Elastic Network Adapter (ENA) ec20' drv=vfio-pci unused=ena
# 
# Network devices using kernel driver
# ===================================
# 0000:00:05.0 'Elastic Network Adapter (ENA) ec20' if=ens5 drv=ena unused=vfio-pci *Active*
# 0000:00:06.0 'Elastic Network Adapter (ENA) ec20' if=ens6 drv=ena unused=vfio-pci 
# 0000:00:08.0 'Elastic Network Adapter (ENA) ec20' if=ens8 drv=ena unused=vfio-pci 
