apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-net-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "ens6",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [{"address": "172.31.111.240/20","gateway": "172.31.96.1"}]
      }
    }'
# eth0 from VPC CNI, net1 from ipvlan ENI with ENA driver, for non-dpdk traffic
# kubectl get network-attachment-definitions
