apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
           {
                "resourceName": "sriov_netdevice_1",
                "selectors": {
                    "vendors": [
                        "1d0f"
                    ],
                    "devices": [
                        "ec20"
                    ],
                    "drivers": [
                        "ena",
                        "igb_uio",
                        "vfio-pci"
                    ],
                    "pciAddresses": [
                        "0000:00:06.0"
                    ]
                }
            },
            {
                "resourceName": "sriov_netdevice_2",
                "selectors": {
                    "vendors": [
                        "1d0f"
                    ],
                    "devices": [
                        "ec20"
                    ],
                    "drivers": [
                        "ena",
                        "igb_uio",
                        "vfio-pci"
                    ],
                    "pciAddresses": [
                        "0000:00:07.0"
                    ]
                }
            }
        ]
    }
# parameter values must refer to VF, not PF
# create VF first to get the parameters for this configmap
#
# sh-5.2$ lspci | grep ENA
# 00:05.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
# 00:06.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
# 00:07.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
#
# sh-5.2$ lspci -nk | grep 00:06.0 -A2  
# 00:06.0 0200: 1d0f:ec20
#        Subsystem: 1d0f:ec20
#        Kernel driver in use: ena
# sh-5.2$ lspci -nk | grep 00:07.0 -A2                                                                                                                                                                                              
# 00:07.0 0200: 1d0f:ec20
#        Subsystem: 1d0f:ec20
#        Kernel driver in use: vfio-pci
# sh-5.2$ 
#
# NOTE: 1d0f is vendor ID, ec20 is VF device ID
#
# Another example on Mellanox CX7 card, vendor ID: 15b3, VF device ID: 1021
#
# sh-5.2$ lspci | grep Mellanox [get the pci ID]
# sh-5.2$ lspci -nk | grep 0000:02:00.0 -A2
# 0000:02:00.0 0200: 15b3:1021
#        Subsystem: 15b3:0022
#        Kernel driver in use: mlx5_core
# sh-5.2$ lspci -nk | grep 0000:02:00.1 -A2
# 0000:02:00.1 0200: 15b3:1021
#        Subsystem: 15b3:0022
#        Kernel driver in use: mlx5_core
# sh-5.2$ 
#
#
#
# [root@ip-10-0-52-219 ~]# lspci -nnk | grep 02:00.0 -A1
# 0000:02:00.0 Ethernet controller [0200]: Mellanox Technologies MT2910 Family [ConnectX-7] [15b3:1021]
#        Subsystem: Mellanox Technologies Device [15b3:0022]
#
# [root@ip-10-0-52-219 ~]# lspci -nnk | grep 02:00.0 -A2
# 0000:02:00.0 Ethernet controller [0200]: Mellanox Technologies MT2910 Family [ConnectX-7] [15b3:1021]
#        Subsystem: Mellanox Technologies Device [15b3:0022]
#        Kernel driver in use: mlx5_core
# [root@ip-10-0-52-219 ~]# 
#        
# [root@ip-10-0-52-219 ~]# lspci -nnk | grep 02:00.0 -A3
# 0000:02:00.0 Ethernet controller [0200]: Mellanox Technologies MT2910 Family [ConnectX-7] [15b3:1021]
#        Subsystem: Mellanox Technologies Device [15b3:0022]
#        Kernel driver in use: mlx5_core
#        Kernel modules: mlx5_core
# [root@ip-10-0-52-219 ~]# 
