### root devices pci based, with vf range listed (6 vf per pf example), from the worker node:
# root@ubuntu:~# lspci | grep Mellanox
# 0000:02:00.0 Ethernet controller: Mellanox Technologies MT2910 Family [ConnectX-7]
# 0000:02:00.1 Ethernet controller: Mellanox Technologies MT2910 Family [ConnectX-7]
# 0001:16:00.0 Ethernet controller: Mellanox Technologies MT2910 Family [ConnectX-7]
# 0001:16:00.1 Ethernet controller: Mellanox Technologies MT2910 Family [ConnectX-7]
# root@ubuntu:~#

apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
           {
                "resourceName": "bmn-mlx-sriov-pf1",
                "resourcePrefix": "sigit.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0000:02:00.0#0-5"
                    ]
                }
            },
           {
                "resourceName": "bmn-mlx-sriov-pf2",
                "resourcePrefix": "sigit.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0000:02:00.1#0-5"
                    ]
                }
            },
            {
                "resourceName": "bmn-mlx-sriov-pf3",
                "resourcePrefix": "sigit.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0001:16:00.0#0-5"
                    ]
                }
            },
            {
                "resourceName": "bmn-mlx-sriov-pf4",
                "resourcePrefix": "sigit.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0001:16:00.1#0-5"
                    ]
                }
            }
        ]
    }
