apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_plugin_test",
                "selectors": {
                    "vendors": ["1d0f"],
                    "devices": ["ec20"], 
                    "drivers": ["ena"]
                }
            }
        ]
    }
