apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
           {
                "resourceName": "sriov_netdevice_1",
                "selectors": {
                    "vendors": [
                        "1d0f"
                    ],
                    "devices": [
                        "ec20"
                    ],
                    "drivers": [
                        "ena",
                        "igb_uio",
                        "vfio-pci"
                    ],
                    "pciAddresses": [
                        "0000:00:06.0"
                    ]
                }
            },
            {
                "resourceName": "sriov_netdevice_2",
                "selectors": {
                    "vendors": [
                        "1d0f"
                    ],
                    "devices": [
                        "ec20"
                    ],
                    "drivers": [
                        "ena",
                        "igb_uio",
                        "vfio-pci"
                    ],
                    "pciAddresses": [
                        "0000:00:07.0"
                    ]
                }
            }
        ]
    }
# parameter values
#
# sh-5.2$ lspci | grep ENA
# 00:05.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
# 00:06.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
# 00:07.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
#
# sh-5.2$ lspci -nk | grep 00:06.0 -A2  
# 00:06.0 0200: 1d0f:ec20
#        Subsystem: 1d0f:ec20
#        Kernel driver in use: ena
# sh-5.2$ lspci -nk | grep 00:07.0 -A2                                                                                                                                                                                              
# 00:07.0 0200: 1d0f:ec20
#        Subsystem: 1d0f:ec20
#        Kernel driver in use: vfio-pci
# sh-5.2$ 
