apiVersion: v1
kind: Pod
metadata:
  name: vpp-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-1
spec:
  containers:
  - name:  app
    image: 337387250630.dkr.ecr.us-east-1.amazonaws.com/ubuntu:vpp
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: 2
        memory: 4Gi
        hugepages-1Gi: 2Gi
        intel.com/sriov_netdevice_1: '1'
        intel.com/sriov_netdevice_2: '1'
      limits:
        cpu: 2
        memory: 4Gi
        hugepages-1Gi: 2Gi
        intel.com/sriov_netdevice_1: '1'
        intel.com/sriov_netdevice_2: '1'
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
